version: '3'
services: 
    web: 
        build: ./ngApp
        ports: 
        - "4200:4200"
        links:
        - node
        volumes:
            "Users\lukas\OneDrive\Pulpit\AngularTaskApp\ngApp\dist\ngApp\html"
    node:
        build: ./server
        ports:
        - "3000:3000"
        links: 
        - "mongo"
    mongo:
        image: mongo
        ports:
        - "27017:27017"